[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "docforest"
version = "0.1.0"
authors = [
  { name="Your Name", email="your.email@example.com" },
]
description = "A package for intelligently chunking structured documents into a hierarchical, contextual tree."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/yourusername/docforest"
Issues = "https://github.com/yourusername/docforest/issues"
